from __future__ import annotations

import json
import time
import zipfile
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

from .nodes_v2_debug import (
    build_analysis_debug,
    build_capabilities,
    build_structure,
    collect_workflow_class_types,
    detect_outputs,
    detect_runtime_requirements,
    extract_operation_candidates,
    hash_json,
    parse_workflow,
    read_runtime_node_definitions,
    section_order,
    slugify,
)


class MobileProfileV2ValidatedDebugExporter:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "profile_name": ("STRING", {"default": "Imported Workflow V2 Validated Debug"}),
                "workflow_json_text": ("STRING", {"multiline": True, "default": "{}"}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("export_path",)
    FUNCTION = "export_profile"
    CATEGORY = "mobile_analyzer/debug"
    OUTPUT_NODE = True

    def export_profile(self, profile_name: str, workflow_json_text: str) -> Tuple[str]:
        workflow = parse_workflow(workflow_json_text)
        workflow_id = hash_json(workflow)
        profile_id = slugify(profile_name) or "imported_workflow_v2_validated_debug"
        class_types = collect_workflow_class_types(workflow)
        runtime_node_defs = read_runtime_node_definitions(class_types)
        operation_candidates = extract_operation_candidates(workflow, runtime_node_defs)
        outputs = detect_outputs(workflow, runtime_node_defs)
        runtime_requirements = detect_runtime_requirements(workflow)
        validation_results = validate_operation_candidates(workflow, operation_candidates)
        fields, patch_targets = build_validated_fields(validation_results)
        warnings = build_validated_warnings(workflow, runtime_node_defs, operation_candidates, validation_results, outputs)
        compatibility = decide_validated_compatibility(fields, patch_targets, outputs, warnings, runtime_requirements)

        app_profile = {
            "schema_version": "2.0-validated-debug",
            "profile_id": profile_id,
            "profile_name": profile_name,
            "profile_version": "0.2.0-validated-debug",
            "workflow_id": workflow_id,
            "workflow_format": "api",
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            "source": {"type": "manual", "name": profile_name, "note": "v2 validated debug profile"},
            "compatibility": compatibility,
            "capabilities": build_capabilities(workflow, operation_candidates, outputs, runtime_node_defs),
            "ui": {
                "field_source": "validated_fields",
                "sections": sorted({field["section"] for field in fields}),
                "safety": "fields are validator-classified but still debug-only",
            },
            "fields": fields,
            "patch_targets": patch_targets,
            "structure": build_structure(workflow, runtime_node_defs),
            "runtime_requirements": runtime_requirements,
            "outputs": outputs,
            "warnings": warnings,
            "validation": {
                "schema_version": "candidate_validation.0.1",
                "summary": summarize_validation_results(validation_results),
                "results": validation_results,
            },
            "debug": {
                "operation_candidates_count": len(operation_candidates),
                "runtime_node_definitions_count": len(runtime_node_defs),
                "note": "Validated debug output. This is still not the production app contract.",
            },
        }
        analysis_debug = build_analysis_debug(workflow, runtime_node_defs, operation_candidates)

        output_dir = Path("output") / "mobile_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        zip_path = output_dir / f"{profile_id}_{timestamp}_v2_validated_debug.zip"

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("workflow.json", json.dumps(workflow, ensure_ascii=False, indent=2))
            zf.writestr("app_profile_v2_validated_debug.json", json.dumps(app_profile, ensure_ascii=False, indent=2))
            zf.writestr("analysis_debug.json", json.dumps(analysis_debug, ensure_ascii=False, indent=2))
            zf.writestr(
                "README.txt",
                "Generated by Mobile Profile V2 Validated Debug Exporter. This output is still debug-only and should not replace the MVP app_profile.json yet.\n",
            )

        return (str(zip_path),)


def validate_operation_candidates(workflow: Dict[str, Any], candidates: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []
    for candidate in candidates:
        node_id = str(candidate.get("node_id", ""))
        input_name = str(candidate.get("input", ""))
        node = workflow.get(node_id) or workflow.get(int(node_id)) if node_id.isdigit() else workflow.get(node_id)
        reasons: List[str] = []
        warnings: List[str] = list(candidate.get("notes", []))
        status = "safe_editable"

        if not isinstance(node, dict):
            status = "disabled"
            reasons.append("Target node was not found in workflow.")
        else:
            inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
            if input_name not in inputs:
                status = "disabled"
                reasons.append("Target input was not found in node inputs.")
            elif is_connection_value(inputs[input_name]):
                status = "preserve_only"
                reasons.append("Target input is a connection, not a direct value.")

        safety_hint = str(candidate.get("safety_hint", ""))
        control_type = str(candidate.get("candidate_control_type", ""))
        value_type = str(candidate.get("normalized_value_type", ""))
        raw_type = str(candidate.get("raw_type", ""))

        if safety_hint == "sensitive_disable_by_default":
            status = "disabled"
            reasons.append("Sensitive credential-like field is disabled by default.")
        elif safety_hint == "file_or_network_review_required":
            status = "review_required"
            reasons.append("File path or URL-like field needs manual safety review.")
        elif safety_hint == "unknown_preserve_by_default":
            status = "preserve_only"
            reasons.append("Unknown field type is preserved but not editable.")

        if control_type in {"unknown", "readonly", ""}:
            status = "preserve_only" if status == "safe_editable" else status
            reasons.append("No safe editable control type was assigned.")

        if value_type in {"unknown", ""}:
            status = "preserve_only" if status == "safe_editable" else status
            reasons.append("No safe value type was assigned.")

        if raw_type.upper() in NON_WIDGET_RUNTIME_TYPES:
            status = "preserve_only" if status == "safe_editable" else status
            reasons.append("Runtime type is normally connection-oriented and should not be directly edited.")

        if not candidate.get("known_runtime_definition"):
            warnings.append("Runtime node definition was unavailable; validation used workflow value/name inference.")

        if candidate.get("section_hint") == "expert_unknown" and status == "safe_editable":
            status = "expert_editable"
            warnings.append("Unknown semantic field. Keep in Expert section until explicitly supported.")

        results.append({
            "candidate_id": candidate.get("candidate_id"),
            "node_id": node_id,
            "input": input_name,
            "class_type": candidate.get("class_type"),
            "status": status,
            "editable": status in {"safe_editable", "expert_editable"},
            "patchable": status in {"safe_editable", "expert_editable"},
            "control_type": control_type,
            "value_type": value_type,
            "raw_type": raw_type,
            "section": candidate.get("section_hint") or "expert_unknown",
            "reasons": reasons or ["Candidate passed basic direct-value validation."],
            "warnings": dedupe_strings(warnings),
            "candidate": candidate,
        })
    return results


def build_validated_fields(validation_results: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    fields: List[Dict[str, Any]] = []
    patch_targets: Dict[str, Any] = {}

    for result in validation_results:
        if not result.get("editable"):
            continue

        candidate = result["candidate"]
        field_id = f"field_{result['node_id']}_{result['input']}"
        target_id = f"pt_{result['node_id']}_{result['input']}"
        section = str(result.get("section") or "expert_unknown")

        fields.append({
            "field_id": field_id,
            "label": field_label(result),
            "description": f"{result.get('class_type')} input `{result.get('input')}` validated as {result.get('status')}",
            "control_type": result.get("control_type"),
            "value_type": result.get("value_type"),
            "section": section,
            "visibility": "visible",
            "state": "active",
            "default": candidate.get("current_value"),
            "current": candidate.get("current_value"),
            "patch_target_ids": [target_id],
            "source": {
                "node_id": result.get("node_id"),
                "class_type": result.get("class_type"),
                "input": result.get("input"),
                "role": semantic_role_from_result(result),
                "known": bool(candidate.get("known_runtime_definition")),
                "source_confidence": candidate.get("source_confidence"),
            },
            "safety": {
                "editable": True,
                "status": result.get("status"),
                "semantic_confidence": semantic_confidence_from_result(result),
                "requires_warning": bool(result.get("warnings")) or result.get("status") == "expert_editable",
                "warnings": result.get("warnings", []),
                "validator_reasons": result.get("reasons", []),
            },
        })

        patch_targets[target_id] = {
            "target_id": target_id,
            "scope": "workflow",
            "node_id": result.get("node_id"),
            "input": result.get("input"),
            "path": [str(result.get("node_id")), "inputs", str(result.get("input"))],
            "value_type": result.get("value_type"),
            "allowed_control_types": [result.get("control_type")],
            "safe": result.get("status") == "safe_editable",
            "debug_safe": result.get("status") in {"safe_editable", "expert_editable"},
            "reason": "Validator confirmed this is a direct value input. Expert fields remain debug-gated.",
            "validator": {
                "required": candidate.get("input_group") == "required",
                "allow_connection_inputs": False,
                "status": result.get("status"),
                "reasons": result.get("reasons", []),
            },
        }

    fields.sort(key=lambda item: (section_order(item["section"]), item["field_id"]))
    return fields, patch_targets


def build_validated_warnings(
    workflow: Dict[str, Any],
    runtime_node_defs: Dict[str, Any],
    candidates: List[Dict[str, Any]],
    validation_results: List[Dict[str, Any]],
    outputs: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    warnings: List[Dict[str, Any]] = []

    for class_type in sorted(collect_workflow_class_types(workflow)):
        if class_type not in runtime_node_defs:
            warnings.append({
                "warning_id": f"missing_runtime_def_{slugify(class_type)}",
                "severity": "medium",
                "type": "missing_runtime_definition",
                "message": f"Runtime node definition was not found for {class_type}.",
                "related_class_type": class_type,
                "requires_user_attention": True,
            })

    for result in validation_results:
        if result.get("status") in {"disabled", "review_required", "preserve_only"}:
            warnings.append({
                "warning_id": f"validator_{result.get('node_id')}_{result.get('input')}",
                "severity": "medium" if result.get("status") != "disabled" else "high",
                "type": "validator_blocked_candidate",
                "message": f"Candidate {result.get('node_id')}.{result.get('input')} is {result.get('status')}.",
                "related_node_ids": [str(result.get("node_id"))],
                "related_input": result.get("input"),
                "reasons": result.get("reasons", []),
                "requires_user_attention": result.get("status") in {"disabled", "review_required"},
            })

    if not outputs:
        warnings.append({
            "warning_id": "no_output_detected",
            "severity": "high",
            "type": "unknown_output",
            "message": "No output node was confidently detected.",
            "requires_user_attention": True,
        })

    if has_class_or_name(workflow, ["openai", "anthropic", "openrouter", "runway", "luma", "kling", "ideogram", "recraft"]):
        warnings.append({
            "warning_id": "external_api_possible",
            "severity": "high",
            "type": "external_api",
            "message": "This workflow may contain external API or partner nodes. Review privacy, credentials, and cost before running.",
            "requires_user_attention": True,
        })

    return dedupe_dicts(warnings)


def decide_validated_compatibility(
    fields: List[Dict[str, Any]],
    patch_targets: Dict[str, Any],
    outputs: List[Dict[str, Any]],
    warnings: List[Dict[str, Any]],
    runtime_requirements: Dict[str, Any],
) -> Dict[str, Any]:
    high_warnings = [warning for warning in warnings if warning.get("severity") == "high"]
    expert_fields = [field for field in fields if field.get("section") == "expert_unknown"]

    if not outputs:
        level = "unsupported"
        safe_to_generate = False
    elif high_warnings:
        level = "partial"
        safe_to_generate = False
    elif runtime_requirements.get("custom_nodes") or expert_fields:
        level = "partial"
        safe_to_generate = True
    else:
        level = "supported"
        safe_to_generate = True

    return {
        "level": level,
        "safe_to_generate": safe_to_generate,
        "safe_to_edit": bool(fields),
        "safe_to_patch": bool(patch_targets),
        "reasons": compatibility_reasons(level, fields, outputs, warnings, expert_fields),
    }


def compatibility_reasons(level: str, fields: List[Dict[str, Any]], outputs: List[Dict[str, Any]], warnings: List[Dict[str, Any]], expert_fields: List[Dict[str, Any]]) -> List[str]:
    reasons = [f"v2 validated debug compatibility level: {level}"]
    reasons.append(f"Validated editable field count: {len(fields)}")
    reasons.append(f"Detected output count: {len(outputs)}")
    if expert_fields:
        reasons.append(f"Expert unknown field count: {len(expert_fields)}")
    if warnings:
        reasons.append(f"Warning count: {len(warnings)}")
    return reasons


def summarize_validation_results(results: List[Dict[str, Any]]) -> Dict[str, Any]:
    by_status: Dict[str, int] = {}
    for result in results:
        status = str(result.get("status", "unknown"))
        by_status[status] = by_status.get(status, 0) + 1
    return {
        "total": len(results),
        "editable": sum(1 for result in results if result.get("editable")),
        "patchable": sum(1 for result in results if result.get("patchable")),
        "by_status": dict(sorted(by_status.items())),
    }


def field_label(result: Dict[str, Any]) -> str:
    role = semantic_role_from_result(result)
    if role != "unknown":
        return role.replace("_", " ").title()
    return f"{result.get('class_type')} / {result.get('input')}"


def semantic_role_from_result(result: Dict[str, Any]) -> str:
    class_type = str(result.get("class_type", ""))
    input_name = str(result.get("input", "")).lower()
    control_type = str(result.get("control_type", ""))

    if class_type == "CLIPTextEncode" and input_name == "text":
        return "prompt_text"
    if input_name in {"seed", "steps", "cfg", "denoise", "sampler_name", "scheduler", "width", "height", "batch_size"}:
        return input_name
    if input_name.endswith("_name") or input_name in {"ckpt_name", "lora_name", "model_name"}:
        return "model_picker"
    if "lora" in class_type.lower() or "lora" in input_name:
        return "lora_control"
    if "controlnet" in class_type.lower() or "control" in input_name:
        return "controlnet_control"
    if control_type in {"image_upload", "mask_editor", "audio_upload", "video_upload"}:
        return control_type
    return "unknown"


def semantic_confidence_from_result(result: Dict[str, Any]) -> str:
    candidate = result.get("candidate", {})
    if result.get("status") == "safe_editable" and candidate.get("known_runtime_definition"):
        return "high"
    if result.get("status") in {"safe_editable", "expert_editable"}:
        return "medium"
    return "unknown"


def is_connection_value(value: Any) -> bool:
    return isinstance(value, list) and len(value) == 2 and isinstance(value[0], (str, int)) and isinstance(value[1], int)


def has_class_or_name(workflow: Dict[str, Any], tokens: List[str]) -> bool:
    for node in workflow.values():
        if not isinstance(node, dict):
            continue
        text = " ".join(str(node.get(key, "")) for key in ["class_type", "_meta", "title"]).lower()
        if any(token in text for token in tokens):
            return True
    return False


def dedupe_strings(values: Iterable[str]) -> List[str]:
    result: List[str] = []
    seen = set()
    for value in values:
        if value not in seen:
            seen.add(value)
            result.append(value)
    return result


def dedupe_dicts(values: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    result: List[Dict[str, Any]] = []
    seen = set()
    for value in values:
        key = json.dumps(value, sort_keys=True, ensure_ascii=False)
        if key not in seen:
            seen.add(key)
            result.append(value)
    return result


NON_WIDGET_RUNTIME_TYPES = {
    "MODEL",
    "CLIP",
    "VAE",
    "CONDITIONING",
    "LATENT",
    "SAMPLER",
    "SIGMAS",
    "GUIDER",
}

NODE_CLASS_MAPPINGS = {"MobileProfileV2ValidatedDebugExporter": MobileProfileV2ValidatedDebugExporter}
NODE_DISPLAY_NAME_MAPPINGS = {"MobileProfileV2ValidatedDebugExporter": "Mobile Profile V2 Validated Debug Exporter"}
