"""MobileProfileExporter skeleton.

This is an early draft. It is intentionally conservative:
- no auto-install
- no model download
- no connection rewiring
- no arbitrary execution
"""

from __future__ import annotations

import hashlib
import json
import time
import zipfile
from pathlib import Path
from typing import Any, Dict, Tuple


class MobileProfileExporter:
    """Export a minimal mobile profile package from workflow JSON."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "profile_name": ("STRING", {"default": "Imported Workflow"}),
                "workflow_json_text": ("STRING", {"multiline": True, "default": "{}"}),
                "visibility_mode": (["simple_first", "show_more", "expert"], {"default": "simple_first"}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("export_path",)
    FUNCTION = "export_profile"
    CATEGORY = "mobile_analyzer"

    def export_profile(self, profile_name: str, workflow_json_text: str, visibility_mode: str) -> Tuple[str]:
        workflow = _parse_workflow(workflow_json_text)
        workflow_id = _hash_json(workflow)
        profile_id = _slugify(profile_name) or "imported_workflow"

        app_profile = build_app_profile(
            workflow=workflow,
            profile_id=profile_id,
            profile_name=profile_name,
            workflow_id=workflow_id,
            visibility_mode=visibility_mode,
        )

        output_dir = Path("output") / "mobile_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)

        timestamp = time.strftime("%Y%m%d_%H%M%S")
        zip_name = f"{profile_id}_{timestamp}.zip"
        zip_path = output_dir / zip_name

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("workflow.json", json.dumps(workflow, ensure_ascii=False, indent=2))
            zf.writestr("app_profile.json", json.dumps(app_profile, ensure_ascii=False, indent=2))
            zf.writestr("source_info.json", json.dumps({"source": "manual_text"}, ensure_ascii=False, indent=2))
            zf.writestr("README.txt", "Generated by ComfyUI-Mobile-Analyzer skeleton.\n")

        return (str(zip_path),)


def _parse_workflow(text: str) -> Dict[str, Any]:
    try:
        value = json.loads(text)
    except Exception as exc:
        raise ValueError(f"Invalid workflow JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError("Workflow JSON must be an object")
    return value


def _hash_json(value: Dict[str, Any]) -> str:
    raw = json.dumps(value, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return "sha256_" + hashlib.sha256(raw).hexdigest()


def _slugify(value: str) -> str:
    out = []
    for ch in value.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in [" ", "-", "_"]:
            out.append("_")
    return "".join(out).strip("_")[:80]


def build_app_profile(
    workflow: Dict[str, Any],
    profile_id: str,
    profile_name: str,
    workflow_id: str,
    visibility_mode: str,
) -> Dict[str, Any]:
    nodes = []
    simple_fields = []
    patch_targets = []

    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        category, visibility, role = classify_node(class_type, inputs)

        nodes.append(
            {
                "node_id": str(node_id),
                "class_type": class_type,
                "category": category,
                "known": class_type in KNOWN_NODE_TYPES,
                "exists_in_comfyui": None,
                "ui_visibility": visibility,
                "editable": visibility in ["simple", "advanced", "expert"],
                "role": role,
            }
        )

        if class_type == "CLIPTextEncode" and isinstance(inputs.get("text"), str):
            field_id = "prompt" if not simple_fields else f"prompt_{node_id}"
            patch_id = f"patch_{field_id}"
            simple_fields.append(make_field(field_id, "Prompt", "textarea", "prompt", node_id, "text", inputs.get("text"), patch_id))
            patch_targets.append(make_patch(patch_id, field_id, node_id, "text", "STRING"))

        if class_type == "KSampler":
            for input_name, value_type, label, ui_type in [
                ("seed", "INT", "Seed", "number"),
                ("steps", "INT", "Steps", "number"),
                ("cfg", "FLOAT", "CFG", "slider"),
                ("sampler_name", "COMBO", "Sampler", "select"),
                ("scheduler", "COMBO", "Scheduler", "select"),
                ("denoise", "FLOAT", "Denoise", "slider"),
            ]:
                if input_name in inputs and not _is_connection(inputs[input_name]):
                    field_id = input_name
                    patch_id = f"patch_{node_id}_{input_name}"
                    simple_fields.append(make_field(field_id, label, ui_type, "basic_sampling", node_id, input_name, inputs[input_name], patch_id))
                    patch_targets.append(make_patch(patch_id, field_id, node_id, input_name, value_type))

    return {
        "schema_version": "1.0",
        "profile_id": profile_id,
        "profile_name": profile_name,
        "profile_version": "0.1.0",
        "workflow_id": workflow_id,
        "workflow_format": "api",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "source": {"type": "manual", "name": profile_name, "url": "", "note": ""},
        "compatibility": {
            "status": "partial",
            "missing_nodes_count": 0,
            "missing_models_count": 0,
            "attention_nodes_count": 0,
            "warnings_count": 1,
        },
        "ui": {"simple": simple_fields, "advanced": [], "expert": []},
        "patch_targets": patch_targets,
        "nodes": nodes,
        "missing_nodes": [],
        "missing_models": [],
        "attention_nodes": [],
        "warnings": ["Skeleton exporter: ComfyUI object_info and model checks are not implemented yet."],
    }


def make_field(field_id, label, ui_type, section, node_id, input_name, default, patch_id):
    return {
        "field_id": str(field_id),
        "label": label,
        "type": ui_type,
        "section": section,
        "ui_visibility": "simple",
        "node_id": str(node_id),
        "input": input_name,
        "default": default,
        "patch_target_id": patch_id,
    }


def make_patch(patch_id, field_id, node_id, input_name, value_type):
    return {
        "patch_target_id": patch_id,
        "field_id": str(field_id),
        "node_id": str(node_id),
        "input": input_name,
        "value_type": value_type,
    }


def classify_node(class_type: str, inputs: Dict[str, Any]):
    if class_type == "KSampler":
        return "sampler", "simple", "main_sampler"
    if class_type == "CLIPTextEncode":
        return "prompt", "simple", "prompt_encoder"
    if class_type in ["LoadImage"]:
        return "image_input", "simple", "input_image"
    if class_type in ["SaveImage", "PreviewImage"]:
        return "image_output", "hidden", "output"
    if class_type in ["VAEEncode", "VAEDecode"]:
        return "vae", "hidden", "pass_through"
    if class_type in ["EmptyLatentImage"]:
        return "latent", "expert", "latent_source"
    if class_type in ["CheckpointLoaderSimple", "UNETLoader", "DualCLIPLoader", "VAELoader"]:
        return "model_loader", "expert", "model_loader"
    if class_type in ["LoraLoader"]:
        return "lora", "advanced", "lora"
    if all(_is_connection(v) for v in inputs.values()):
        return "unknown", "hidden", "pass_through_unknown"
    return "unknown", "expert", "unknown"


def _is_connection(value: Any) -> bool:
    return isinstance(value, list) and len(value) == 2 and isinstance(value[0], str)


KNOWN_NODE_TYPES = {
    "KSampler",
    "CLIPTextEncode",
    "LoadImage",
    "SaveImage",
    "PreviewImage",
    "EmptyLatentImage",
    "CheckpointLoaderSimple",
    "UNETLoader",
    "DualCLIPLoader",
    "VAELoader",
    "VAEEncode",
    "VAEDecode",
    "LoraLoader",
}


NODE_CLASS_MAPPINGS = {
    "MobileProfileExporter": MobileProfileExporter,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "MobileProfileExporter": "Mobile Profile Exporter",
}
