from __future__ import annotations

import hashlib
import json
import time
import zipfile
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


class MobileProfileV2DebugExporter:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "profile_name": ("STRING", {"default": "Imported Workflow V2 Debug"}),
                "workflow_json_text": ("STRING", {"multiline": True, "default": "{}"}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("export_path",)
    FUNCTION = "export_profile"
    CATEGORY = "mobile_analyzer/debug"
    OUTPUT_NODE = True

    def export_profile(self, profile_name: str, workflow_json_text: str) -> Tuple[str]:
        workflow = parse_workflow(workflow_json_text)
        workflow_id = hash_json(workflow)
        profile_id = slugify(profile_name) or "imported_workflow_v2_debug"
        class_types = collect_workflow_class_types(workflow)
        runtime_node_defs = read_runtime_node_definitions(class_types)
        operation_candidates = extract_operation_candidates(workflow, runtime_node_defs)
        app_profile_v2 = build_app_profile_v2_debug(
            workflow=workflow,
            profile_id=profile_id,
            profile_name=profile_name,
            workflow_id=workflow_id,
            runtime_node_defs=runtime_node_defs,
            operation_candidates=operation_candidates,
        )
        analysis_debug = build_analysis_debug(workflow, runtime_node_defs, operation_candidates)

        output_dir = Path("output") / "mobile_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        zip_path = output_dir / f"{profile_id}_{timestamp}_v2_debug.zip"

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("workflow.json", json.dumps(workflow, ensure_ascii=False, indent=2))
            zf.writestr("app_profile_v2_debug.json", json.dumps(app_profile_v2, ensure_ascii=False, indent=2))
            zf.writestr("analysis_debug.json", json.dumps(analysis_debug, ensure_ascii=False, indent=2))
            zf.writestr(
                "README.txt",
                "Generated by Mobile Profile V2 Debug Exporter. This output is for schema validation and should not replace the MVP app_profile.json yet.\n",
            )

        return (str(zip_path),)


def parse_workflow(text: str) -> Dict[str, Any]:
    value = json.loads(text)
    if not isinstance(value, dict):
        raise ValueError("Workflow JSON must be an object")
    return value


def hash_json(value: Dict[str, Any]) -> str:
    raw = json.dumps(value, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return "sha256_" + hashlib.sha256(raw).hexdigest()


def slugify(value: str) -> str:
    chars = []
    for ch in value.lower():
        if ch.isalnum():
            chars.append(ch)
        elif ch in [" ", "-", "_"]:
            chars.append("_")
    return "".join(chars).strip("_")[:80]


def build_app_profile_v2_debug(
    workflow: Dict[str, Any],
    profile_id: str,
    profile_name: str,
    workflow_id: str,
    runtime_node_defs: Dict[str, Any],
    operation_candidates: List[Dict[str, Any]],
) -> Dict[str, Any]:
    fields, patch_targets, field_warnings = build_v2_fields_and_patch_targets(operation_candidates)
    outputs = detect_outputs(workflow, runtime_node_defs)
    warnings = build_warnings(workflow, runtime_node_defs, operation_candidates, field_warnings, outputs)
    runtime_requirements = detect_runtime_requirements(workflow)
    structure = build_structure(workflow, runtime_node_defs)

    compatibility_level, safe_to_generate, safe_to_edit = decide_compatibility(
        fields=fields,
        outputs=outputs,
        warnings=warnings,
        runtime_requirements=runtime_requirements,
    )

    return {
        "schema_version": "2.0-debug",
        "profile_id": profile_id,
        "profile_name": profile_name,
        "profile_version": "0.1.0-debug",
        "workflow_id": workflow_id,
        "workflow_format": "api",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "source": {"type": "manual", "name": profile_name, "note": "v2 debug profile"},
        "compatibility": {
            "level": compatibility_level,
            "safe_to_generate": safe_to_generate,
            "safe_to_edit": safe_to_edit,
            "safe_to_patch": bool(patch_targets),
            "reasons": compatibility_reasons(compatibility_level, warnings, outputs, fields),
        },
        "capabilities": build_capabilities(workflow, operation_candidates, outputs, runtime_node_defs),
        "ui": {
            "field_source": "fields",
            "sections": sorted({field["section"] for field in fields}),
        },
        "fields": fields,
        "patch_targets": patch_targets,
        "structure": structure,
        "runtime_requirements": runtime_requirements,
        "outputs": outputs,
        "warnings": warnings,
        "debug": {
            "operation_candidates_count": len(operation_candidates),
            "runtime_node_definitions_count": len(runtime_node_defs),
            "note": "Debug-only v2 profile. Keep current MVP app_profile.json stable until the app migrates.",
        },
    }


def build_v2_fields_and_patch_targets(operation_candidates: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], Dict[str, Any], List[Dict[str, Any]]]:
    fields: List[Dict[str, Any]] = []
    patch_targets: Dict[str, Any] = {}
    warnings: List[Dict[str, Any]] = []

    for candidate in operation_candidates:
        if not candidate_should_be_field(candidate):
            if candidate.get("safety_hint") in {"sensitive_disable_by_default", "file_or_network_review_required"}:
                warnings.append(candidate_warning(candidate, "Candidate disabled pending safety review."))
            continue

        field_id = f"field_{candidate['node_id']}_{candidate['input']}"
        target_id = f"pt_{candidate['node_id']}_{candidate['input']}"
        requires_warning = bool(candidate.get("notes")) or candidate.get("source_confidence") != "runtime_definition"
        section = candidate.get("section_hint") or "expert_unknown"
        control_type = candidate.get("candidate_control_type") or "unknown"
        value_type = candidate.get("normalized_value_type") or "unknown"

        fields.append({
            "field_id": field_id,
            "label": build_field_label(candidate),
            "description": build_field_description(candidate),
            "control_type": control_type,
            "value_type": value_type,
            "section": section,
            "visibility": "visible" if section != "hidden" else "hidden",
            "state": "active",
            "default": candidate.get("current_value"),
            "current": candidate.get("current_value"),
            "patch_target_ids": [target_id],
            "source": {
                "node_id": candidate.get("node_id"),
                "class_type": candidate.get("class_type"),
                "input": candidate.get("input"),
                "role": semantic_role(candidate),
                "known": candidate.get("class_type") in KNOWN_NODE_TYPES,
                "source_confidence": candidate.get("source_confidence"),
            },
            "safety": {
                "editable": True,
                "semantic_confidence": semantic_confidence(candidate),
                "requires_warning": requires_warning,
                "warnings": candidate.get("notes", []),
            },
        })

        patch_targets[target_id] = {
            "target_id": target_id,
            "scope": "workflow",
            "node_id": candidate.get("node_id"),
            "input": candidate.get("input"),
            "path": [str(candidate.get("node_id")), "inputs", str(candidate.get("input"))],
            "value_type": value_type,
            "allowed_control_types": [control_type],
            "safe": True,
            "reason": "Debug v2 exact value input candidate. Still requires runtime validation before MVP app use.",
            "validator": {
                "required": candidate.get("input_group") == "required",
                "allow_connection_inputs": False,
            },
        }

    fields.sort(key=lambda item: (section_order(item["section"]), item["field_id"]))
    return fields, patch_targets, warnings


def candidate_should_be_field(candidate: Dict[str, Any]) -> bool:
    if candidate.get("safety_hint") in {"sensitive_disable_by_default", "file_or_network_review_required", "unknown_preserve_by_default"}:
        return False
    if candidate.get("candidate_control_type") in {"unknown", "readonly"}:
        return False
    if candidate.get("normalized_value_type") == "unknown":
        return False
    return True


def build_field_label(candidate: Dict[str, Any]) -> str:
    role = semantic_role(candidate)
    if role != "unknown":
        return role.replace("_", " ").title()
    return f"{candidate.get('class_type')} / {candidate.get('input')}"


def build_field_description(candidate: Dict[str, Any]) -> str:
    return f"{candidate.get('class_type')} input `{candidate.get('input')}` as {candidate.get('raw_type')}"


def semantic_role(candidate: Dict[str, Any]) -> str:
    class_type = str(candidate.get("class_type", ""))
    input_name = str(candidate.get("input", "")).lower()

    if class_type == "CLIPTextEncode" and input_name == "text":
        return "prompt_text"
    if input_name in {"seed", "steps", "cfg", "denoise", "sampler_name", "scheduler", "width", "height", "batch_size"}:
        return input_name
    if input_name in MODEL_PICKER_INPUT_NAMES:
        return "model_picker"
    if "lora" in class_type.lower() or "lora" in input_name:
        return "lora_control"
    if "controlnet" in class_type.lower() or "control" in input_name:
        return "controlnet_control"
    if candidate.get("candidate_control_type") in {"image_upload", "mask_editor", "audio_upload", "video_upload"}:
        return candidate.get("candidate_control_type", "media_input")
    return "unknown"


def semantic_confidence(candidate: Dict[str, Any]) -> str:
    if candidate.get("class_type") in KNOWN_NODE_TYPES:
        return "high"
    if candidate.get("source_confidence") == "runtime_definition":
        return "medium"
    return "unknown"


def section_order(section: str) -> int:
    order = {
        "core": 0,
        "basic": 1,
        "media": 2,
        "model": 3,
        "advanced": 4,
        "wildcard": 5,
        "branch": 6,
        "subgraph": 7,
        "expert_unknown": 8,
        "debug": 9,
        "hidden": 10,
    }
    return order.get(section, 99)


def build_capabilities(
    workflow: Dict[str, Any],
    operation_candidates: List[Dict[str, Any]],
    outputs: List[Dict[str, Any]],
    runtime_node_defs: Dict[str, Any],
) -> Dict[str, Any]:
    return {
        "input_types": sorted({str(candidate.get("normalized_value_type")) for candidate in operation_candidates if candidate.get("normalized_value_type")}),
        "control_types": sorted({str(candidate.get("candidate_control_type")) for candidate in operation_candidates if candidate.get("candidate_control_type")}),
        "output_types": sorted({str(output.get("output_type")) for output in outputs}),
        "has_subgraphs": has_class_or_name(workflow, ["subgraph"]),
        "has_bypass_states": False,
        "has_switches": has_class_or_name(workflow, ["switch", "chooser", "select"]),
        "has_wildcards": has_class_or_name(workflow, ["wildcard", "random line", "dynamic prompt"]),
        "has_llm_nodes": has_class_or_name(workflow, ["ollama", "gemma", "llm", "openai", "anthropic", "openrouter"]),
        "has_external_api_nodes": has_class_or_name(workflow, ["openai", "anthropic", "openrouter", "runway", "luma", "kling", "ideogram", "recraft"]),
        "has_unknown_custom_nodes": any(class_type not in runtime_node_defs for class_type in collect_workflow_class_types(workflow)),
        "has_expert_editable_fields": any(candidate.get("section_hint") == "expert_unknown" for candidate in operation_candidates),
    }


def build_structure(workflow: Dict[str, Any], runtime_node_defs: Dict[str, Any]) -> Dict[str, Any]:
    nodes = []
    edges = []
    output_nodes = []

    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        runtime_def = runtime_node_defs.get(class_type, {}) if isinstance(runtime_node_defs.get(class_type, {}), dict) else {}
        nodes.append({
            "node_id": str(node_id),
            "class_type": class_type,
            "known_runtime_definition": bool(runtime_def),
            "output_node": bool(runtime_def.get("output_node")) or class_type in IMAGE_OUTPUT_NODE_TYPES,
        })
        if bool(runtime_def.get("output_node")) or class_type in IMAGE_OUTPUT_NODE_TYPES:
            output_nodes.append(str(node_id))

        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        for input_name, value in inputs.items():
            if is_connection(value):
                edges.append({
                    "from_node_id": str(value[0]),
                    "from_output_index": value[1],
                    "to_node_id": str(node_id),
                    "to_input": str(input_name),
                })

    return {
        "nodes": nodes,
        "edges": edges,
        "subgraphs": [],
        "branches": [],
        "switches": [],
        "bypass_states": [],
        "active_paths": [],
        "set_get_links": [],
        "output_nodes": output_nodes,
        "note": "Subgraph/bypass/switch structures are placeholders in this first v2 debug implementation.",
    }


def detect_outputs(workflow: Dict[str, Any], runtime_node_defs: Dict[str, Any]) -> List[Dict[str, Any]]:
    outputs: List[Dict[str, Any]] = []
    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        runtime_def = runtime_node_defs.get(class_type, {}) if isinstance(runtime_node_defs.get(class_type, {}), dict) else {}
        output_type = infer_output_type(class_type, runtime_def)
        if output_type == "none":
            continue
        outputs.append({
            "output_id": f"output_{node_id}",
            "output_type": output_type,
            "node_id": str(node_id),
            "class_type": class_type,
            "viewer": viewer_for_output_type(output_type),
            "safe_to_display": output_type in {"image", "video", "audio", "text", "json", "svg", "file", "unknown"},
            "safe_to_save": True,
            "warnings": [] if output_type != "unknown" else ["Output type could not be confidently classified."],
        })
    return outputs


def infer_output_type(class_type: str, runtime_def: Dict[str, Any]) -> str:
    return_types = runtime_def.get("return_types") or []
    return_types_upper = {str(item).upper() for item in return_types} if isinstance(return_types, list) else set()

    if class_type in IMAGE_OUTPUT_NODE_TYPES or "IMAGE" in return_types_upper:
        return "image"
    if class_type in VIDEO_OUTPUT_NODE_TYPES or "VIDEO" in return_types_upper:
        return "video"
    if class_type in AUDIO_OUTPUT_NODE_TYPES or "AUDIO" in return_types_upper:
        return "audio"
    if "STRING" in return_types_upper:
        return "text"
    if "JSON" in return_types_upper:
        return "json"
    if "SVG" in return_types_upper:
        return "svg"
    if "MESH" in return_types_upper:
        return "3d"
    if bool(runtime_def.get("output_node")):
        return "unknown"
    return "none"


def viewer_for_output_type(output_type: str) -> str:
    return {
        "image": "image_viewer",
        "video": "video_viewer",
        "audio": "audio_player",
        "text": "text_viewer",
        "json": "json_viewer",
        "svg": "svg_viewer",
        "3d": "file_viewer",
        "file": "file_viewer",
        "unknown": "unknown_output_viewer",
    }.get(output_type, "unknown_output_viewer")


def detect_runtime_requirements(workflow: Dict[str, Any]) -> Dict[str, Any]:
    models: List[Dict[str, Any]] = []
    custom_nodes: List[Dict[str, Any]] = []
    for node in workflow.values():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        models.extend(detect_model_refs(class_type, inputs))
        if class_type not in KNOWN_NODE_TYPES:
            custom_nodes.append({"class_type": class_type, "status": "unverified"})
    return {
        "models": dedupe(models),
        "loras": [item for item in dedupe(models) if item.get("type") == "lora"],
        "vae": [item for item in dedupe(models) if item.get("type") == "vae"],
        "clip": [],
        "controlnet": [],
        "upscale_models": [],
        "custom_nodes": dedupe(custom_nodes),
        "python_packages": [],
        "external_services": [],
        "credentials": [],
    }


def build_warnings(
    workflow: Dict[str, Any],
    runtime_node_defs: Dict[str, Any],
    operation_candidates: List[Dict[str, Any]],
    field_warnings: List[Dict[str, Any]],
    outputs: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    warnings: List[Dict[str, Any]] = list(field_warnings)
    class_types = collect_workflow_class_types(workflow)

    for class_type in sorted(class_types):
        if class_type not in runtime_node_defs:
            warnings.append({
                "warning_id": f"missing_runtime_def_{slugify(class_type)}",
                "severity": "medium",
                "type": "missing_runtime_definition",
                "message": f"Runtime node definition was not found for {class_type}.",
                "related_class_type": class_type,
                "requires_user_attention": True,
            })

    for candidate in operation_candidates:
        if candidate.get("safety_hint") == "sensitive_disable_by_default":
            warnings.append(candidate_warning(candidate, "Sensitive field detected and disabled by default."))
        elif candidate.get("safety_hint") == "file_or_network_review_required":
            warnings.append(candidate_warning(candidate, "File path or URL-like field requires safety review."))

    if not outputs:
        warnings.append({
            "warning_id": "no_output_detected",
            "severity": "high",
            "type": "unknown_output",
            "message": "No output node was confidently detected.",
            "requires_user_attention": True,
        })

    if has_class_or_name(workflow, ["openai", "anthropic", "openrouter", "runway", "luma", "kling", "ideogram", "recraft"]):
        warnings.append({
            "warning_id": "external_api_possible",
            "severity": "high",
            "type": "external_api",
            "message": "This workflow may contain external API or partner nodes. Review privacy, credentials, and cost before running.",
            "requires_user_attention": True,
        })

    return dedupe_warnings(warnings)


def candidate_warning(candidate: Dict[str, Any], message: str) -> Dict[str, Any]:
    return {
        "warning_id": f"candidate_{candidate.get('node_id')}_{candidate.get('input')}",
        "severity": "medium",
        "type": "candidate_review",
        "message": message,
        "related_node_ids": [str(candidate.get("node_id"))],
        "related_input": candidate.get("input"),
        "requires_user_attention": True,
    }


def decide_compatibility(
    fields: List[Dict[str, Any]],
    outputs: List[Dict[str, Any]],
    warnings: List[Dict[str, Any]],
    runtime_requirements: Dict[str, Any],
) -> Tuple[str, bool, bool]:
    high_warnings = [warning for warning in warnings if warning.get("severity") == "high"]
    if not outputs:
        return "unsupported", False, bool(fields)
    if high_warnings:
        return "partial", False, bool(fields)
    if runtime_requirements.get("custom_nodes"):
        return "partial", True, bool(fields)
    return "supported", True, bool(fields)


def compatibility_reasons(
    level: str,
    warnings: List[Dict[str, Any]],
    outputs: List[Dict[str, Any]],
    fields: List[Dict[str, Any]],
) -> List[str]:
    reasons = [f"v2 debug compatibility level: {level}"]
    if outputs:
        reasons.append(f"Detected {len(outputs)} output node(s).")
    else:
        reasons.append("No output nodes were confidently detected.")
    if fields:
        reasons.append(f"Generated {len(fields)} debug field(s) from operation candidates.")
    else:
        reasons.append("No editable debug fields were generated.")
    if warnings:
        reasons.append(f"Generated {len(warnings)} warning(s).")
    return reasons


def collect_workflow_class_types(workflow: Dict[str, Any]) -> set[str]:
    result: set[str] = set()
    for node in workflow.values():
        if isinstance(node, dict) and node.get("class_type"):
            result.add(str(node.get("class_type")))
    return result


def read_runtime_node_definitions(class_types: Iterable[str]) -> Dict[str, Any]:
    try:
        import nodes as comfy_nodes  # type: ignore
    except Exception:
        return {}

    mappings = getattr(comfy_nodes, "NODE_CLASS_MAPPINGS", {})
    if not isinstance(mappings, dict):
        return {}

    result: Dict[str, Any] = {}
    for class_type in sorted(set(str(item) for item in class_types)):
        node_class = mappings.get(class_type)
        if node_class is None:
            continue
        result[class_type] = extract_runtime_node_definition(class_type, node_class)
    return result


def extract_runtime_node_definition(class_type: str, node_class: Any) -> Dict[str, Any]:
    input_types: Dict[str, Any] = {}
    input_error: Optional[str] = None
    try:
        input_types_fn = getattr(node_class, "INPUT_TYPES", None)
        if callable(input_types_fn):
            raw_input_types = input_types_fn()
            if isinstance(raw_input_types, dict):
                input_types = normalize_input_types(raw_input_types)
    except Exception as exc:
        input_error = f"{type(exc).__name__}: {exc}"

    return {
        "class_type": class_type,
        "category": to_json_safe(getattr(node_class, "CATEGORY", None)),
        "return_types": to_json_safe(getattr(node_class, "RETURN_TYPES", None)),
        "return_names": to_json_safe(getattr(node_class, "RETURN_NAMES", None)),
        "function": to_json_safe(getattr(node_class, "FUNCTION", None)),
        "output_node": bool(getattr(node_class, "OUTPUT_NODE", False)),
        "inputs": input_types,
        "input_error": input_error,
    }


def normalize_input_types(raw_input_types: Dict[str, Any]) -> Dict[str, Any]:
    normalized: Dict[str, Any] = {}
    for group_name in ["required", "optional", "hidden"]:
        raw_group = raw_input_types.get(group_name, {})
        if not isinstance(raw_group, dict):
            continue
        normalized[group_name] = {}
        for input_name, spec in raw_group.items():
            normalized[group_name][str(input_name)] = normalize_input_spec(spec)
    return normalized


def normalize_input_spec(spec: Any) -> Dict[str, Any]:
    raw_type: Any = None
    config: Dict[str, Any] = {}
    options: Optional[List[Any]] = None

    if isinstance(spec, tuple) and spec:
        raw_type = spec[0]
        if len(spec) > 1 and isinstance(spec[1], dict):
            config = spec[1]
    elif isinstance(spec, list):
        raw_type = spec
    elif isinstance(spec, str):
        raw_type = spec
    else:
        raw_type = type(spec).__name__

    if isinstance(raw_type, list):
        options = [to_json_safe(value) for value in raw_type]
        comfy_type = "COMBO"
    else:
        comfy_type = str(raw_type)

    return {
        "raw_type": comfy_type,
        "normalized_value_type": normalize_value_type(comfy_type),
        "candidate_control_type": default_control_type(comfy_type, config=config),
        "config": to_json_safe(config),
        "options": options,
    }


def extract_operation_candidates(workflow: Dict[str, Any], runtime_node_defs: Dict[str, Any]) -> List[Dict[str, Any]]:
    candidates: List[Dict[str, Any]] = []
    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        runtime_def = runtime_node_defs.get(class_type, {}) if isinstance(runtime_node_defs.get(class_type, {}), dict) else {}
        runtime_inputs = runtime_def.get("inputs", {}) if isinstance(runtime_def.get("inputs", {}), dict) else {}

        for input_name, current_value in inputs.items():
            if is_connection(current_value):
                continue
            input_meta, input_group = find_runtime_input_meta(runtime_inputs, str(input_name))
            inferred_type = infer_input_type(str(input_name), current_value)
            raw_type = str(input_meta.get("raw_type") or inferred_type)
            normalized_value_type = str(input_meta.get("normalized_value_type") or normalize_value_type(raw_type))
            control_type = str(input_meta.get("candidate_control_type") or default_control_type(raw_type, input_name=str(input_name)))
            safety_hint = safety_hint_for_candidate(raw_type, control_type, str(input_name))
            candidates.append({
                "candidate_id": f"candidate_{node_id}_{input_name}",
                "node_id": str(node_id),
                "class_type": class_type,
                "input": str(input_name),
                "input_group": input_group,
                "raw_type": raw_type,
                "normalized_value_type": normalized_value_type,
                "candidate_control_type": control_type,
                "current_value": to_json_safe(current_value),
                "source_confidence": "runtime_definition" if input_meta else "value_inference",
                "known_runtime_definition": bool(runtime_def),
                "known_input_definition": bool(input_meta),
                "section_hint": section_hint_for_candidate(class_type, str(input_name), raw_type, control_type),
                "safety_hint": safety_hint,
                "notes": candidate_notes(class_type, str(input_name), raw_type, input_meta),
            })
    return candidates


def build_analysis_debug(workflow: Dict[str, Any], runtime_node_defs: Dict[str, Any], operation_candidates: List[Dict[str, Any]]) -> Dict[str, Any]:
    class_types = sorted(collect_workflow_class_types(workflow))
    missing_runtime_defs = [class_type for class_type in class_types if class_type not in runtime_node_defs]
    return {
        "schema_version": "analysis_debug.0.2",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "purpose": "Debug-only operation candidate output used by app_profile_v2_debug.json.",
        "workflow_summary": {
            "node_count": sum(1 for value in workflow.values() if isinstance(value, dict) and "class_type" in value),
            "class_types": class_types,
        },
        "runtime_node_definitions": {
            "found_count": len(runtime_node_defs),
            "missing_class_types": missing_runtime_defs,
            "definitions": runtime_node_defs,
        },
        "operation_candidates": operation_candidates,
        "candidate_summary": summarize_operation_candidates(operation_candidates),
        "safety_note": "These are operation candidates, not final production editable fields. v2 debug fields are still not the MVP contract.",
    }


def find_runtime_input_meta(runtime_inputs: Dict[str, Any], input_name: str) -> Tuple[Dict[str, Any], Optional[str]]:
    for group_name in ["required", "optional", "hidden"]:
        group = runtime_inputs.get(group_name, {})
        if isinstance(group, dict) and isinstance(group.get(input_name), dict):
            return group[input_name], group_name
    return {}, None


def infer_input_type(input_name: str, value: Any) -> str:
    lower_name = input_name.lower()
    if lower_name in {"image", "init_image", "reference_image"} or lower_name.endswith("_image"):
        return "IMAGE" if isinstance(value, str) else "UNKNOWN"
    if "mask" in lower_name:
        return "MASK" if isinstance(value, str) else "UNKNOWN"
    if "audio" in lower_name or "voice" in lower_name or lower_name in {"bgm", "sound"}:
        return "AUDIO" if isinstance(value, str) else "UNKNOWN"
    if "video" in lower_name or lower_name in {"movie", "clip"}:
        return "VIDEO" if isinstance(value, str) else "UNKNOWN"
    if lower_name in MODEL_PICKER_INPUT_NAMES:
        return "COMBO"
    if isinstance(value, bool):
        return "BOOLEAN"
    if isinstance(value, int) and not isinstance(value, bool):
        return "INT"
    if isinstance(value, float):
        return "FLOAT"
    if isinstance(value, str):
        return "STRING"
    if isinstance(value, (list, dict)):
        return "JSON"
    return "UNKNOWN"


def normalize_value_type(raw_type: str) -> str:
    upper_type = raw_type.upper()
    if upper_type in {"STRING", "COMBO"}:
        return "string"
    if upper_type in {"INT", "INTEGER"}:
        return "integer"
    if upper_type in {"FLOAT", "DOUBLE", "NUMBER"}:
        return "float"
    if upper_type in {"BOOLEAN", "BOOL"}:
        return "boolean"
    if upper_type == "IMAGE":
        return "image"
    if upper_type == "MASK":
        return "mask"
    if upper_type == "AUDIO":
        return "audio"
    if upper_type == "VIDEO":
        return "video"
    if upper_type == "JSON":
        return "json"
    return "unknown"


def default_control_type(raw_type: str, config: Optional[Dict[str, Any]] = None, input_name: str = "") -> str:
    upper_type = raw_type.upper()
    config = config or {}
    lower_name = input_name.lower()
    if upper_type == "STRING":
        if config.get("multiline") or any(token in lower_name for token in ["prompt", "text", "caption", "template"]):
            return "textarea"
        return "text"
    if upper_type in {"INT", "INTEGER"}:
        return "seed" if "seed" in lower_name else "integer"
    if upper_type in {"FLOAT", "DOUBLE", "NUMBER"}:
        return "slider" if any(key in config for key in ["min", "max", "step"]) else "float"
    if upper_type in {"BOOLEAN", "BOOL"}:
        return "switch"
    if upper_type == "COMBO":
        return "model_picker" if lower_name in MODEL_PICKER_INPUT_NAMES or lower_name.endswith("_name") else "select"
    if upper_type == "IMAGE":
        return "image_upload"
    if upper_type == "MASK":
        return "mask_editor"
    if upper_type == "AUDIO":
        return "audio_upload"
    if upper_type == "VIDEO":
        return "video_upload"
    if upper_type == "JSON":
        return "readonly"
    return "unknown"


def section_hint_for_candidate(class_type: str, input_name: str, raw_type: str, control_type: str) -> str:
    lower_class = class_type.lower()
    lower_input = input_name.lower()
    if "prompt" in lower_input or lower_input in {"text", "system_prompt", "negative"}:
        return "core"
    if lower_input in {"seed", "steps", "cfg", "denoise", "sampler_name", "scheduler", "width", "height", "batch_size"}:
        return "basic"
    if "lora" in lower_class or "lora" in lower_input:
        return "model"
    if "controlnet" in lower_class or "control" in lower_input:
        return "advanced"
    if control_type in {"image_upload", "mask_editor", "audio_upload", "video_upload", "file_upload"}:
        return "media"
    if control_type in {"model_picker", "select"}:
        return "model"
    if raw_type.upper() in {"STRING", "INT", "FLOAT", "BOOLEAN", "COMBO"}:
        return "expert_unknown" if class_type not in KNOWN_NODE_TYPES else "advanced"
    return "hidden"


def safety_hint_for_candidate(raw_type: str, control_type: str, input_name: str) -> str:
    upper_type = raw_type.upper()
    lower_name = input_name.lower()
    if lower_name in {"api_key", "token", "password", "secret", "credential"} or "api_key" in lower_name:
        return "sensitive_disable_by_default"
    if "path" in lower_name or "url" in lower_name:
        return "file_or_network_review_required"
    if upper_type in {"STRING", "INT", "FLOAT", "BOOLEAN", "COMBO", "IMAGE", "MASK", "AUDIO", "VIDEO"}:
        return "candidate_requires_validator"
    if control_type == "readonly":
        return "preserve_only"
    return "unknown_preserve_by_default"


def candidate_notes(class_type: str, input_name: str, raw_type: str, input_meta: Dict[str, Any]) -> List[str]:
    notes: List[str] = []
    if not input_meta:
        notes.append("Runtime input definition missing; type inferred from current value/name.")
    if class_type not in KNOWN_NODE_TYPES:
        notes.append("Unknown or not-yet-semantic-classified node; expose only after validator approval.")
    if raw_type.upper() in NON_WIDGET_RUNTIME_TYPES:
        notes.append("Runtime type is normally connection-oriented; keep read-only unless a known safe widget pattern exists.")
    return notes


def summarize_operation_candidates(candidates: List[Dict[str, Any]]) -> Dict[str, Any]:
    by_type: Dict[str, int] = {}
    by_control: Dict[str, int] = {}
    by_safety: Dict[str, int] = {}
    for candidate in candidates:
        by_type[str(candidate.get("raw_type", "unknown"))] = by_type.get(str(candidate.get("raw_type", "unknown")), 0) + 1
        by_control[str(candidate.get("candidate_control_type", "unknown"))] = by_control.get(str(candidate.get("candidate_control_type", "unknown")), 0) + 1
        by_safety[str(candidate.get("safety_hint", "unknown"))] = by_safety.get(str(candidate.get("safety_hint", "unknown")), 0) + 1
    return {
        "total": len(candidates),
        "by_raw_type": dict(sorted(by_type.items())),
        "by_candidate_control_type": dict(sorted(by_control.items())),
        "by_safety_hint": dict(sorted(by_safety.items())),
    }


def detect_model_refs(class_type: str, inputs: Dict[str, Any]) -> List[Dict[str, Any]]:
    rules = {
        "CheckpointLoaderSimple": [("ckpt_name", "checkpoint", "models/checkpoints")],
        "UNETLoader": [("unet_name", "unet", "models/unet")],
        "VAELoader": [("vae_name", "vae", "models/vae")],
        "LoraLoader": [("lora_name", "lora", "models/loras")],
    }
    refs = []
    for input_name, model_type, path_hint in rules.get(class_type, []):
        value = inputs.get(input_name)
        if isinstance(value, str) and value:
            refs.append({"type": model_type, "name": value, "path_hint": path_hint})
    return refs


def is_connection(value: Any) -> bool:
    return isinstance(value, list) and len(value) == 2 and isinstance(value[0], (str, int)) and isinstance(value[1], int)


def has_class_or_name(workflow: Dict[str, Any], tokens: List[str]) -> bool:
    for node in workflow.values():
        if not isinstance(node, dict):
            continue
        text = " ".join(str(node.get(key, "")) for key in ["class_type", "_meta", "title"]).lower()
        if any(token in text for token in tokens):
            return True
    return False


def dedupe(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = set()
    result = []
    for item in items:
        key = json.dumps(item, sort_keys=True, ensure_ascii=False)
        if key not in seen:
            seen.add(key)
            result.append(item)
    return result


def dedupe_warnings(warnings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return dedupe(warnings)


def to_json_safe(value: Any) -> Any:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, tuple):
        return [to_json_safe(item) for item in value]
    if isinstance(value, list):
        return [to_json_safe(item) for item in value]
    if isinstance(value, dict):
        return {str(key): to_json_safe(item) for key, item in value.items()}
    return str(value)


KNOWN_NODE_TYPES = {
    "KSampler",
    "CLIPTextEncode",
    "LoadImage",
    "SaveImage",
    "PreviewImage",
    "EmptyLatentImage",
    "CheckpointLoaderSimple",
    "UNETLoader",
    "DualCLIPLoader",
    "VAELoader",
    "VAEEncode",
    "VAEDecode",
    "LoraLoader",
}

IMAGE_OUTPUT_NODE_TYPES = {"SaveImage", "PreviewImage"}

# Exact class-type matches used only as a fallback when runtime node metadata
# (RETURN_TYPES/output_node from /object_info) is unavailable for the node.
# SaveVideo/SaveAudio*/PreviewAudio were confirmed via a live /object_info
# query against a local ComfyUI 0.27.0 instance. VHS_VideoCombine
# (ComfyUI-VideoHelperSuite) is a widely used community node but was not
# installed in that verification environment, so its existence here is
# unconfirmed locally even though it is a well-known third-party node.
VIDEO_OUTPUT_NODE_TYPES = {"SaveVideo", "VHS_VideoCombine"}
AUDIO_OUTPUT_NODE_TYPES = {"SaveAudio", "SaveAudioAdvanced", "SaveAudioMP3", "SaveAudioOpus", "PreviewAudio"}

MODEL_PICKER_INPUT_NAMES = {
    "ckpt_name",
    "checkpoint",
    "unet_name",
    "vae_name",
    "clip_name",
    "lora_name",
    "control_net_name",
    "controlnet_name",
    "model_name",
    "sampler_name",
    "scheduler",
}

NON_WIDGET_RUNTIME_TYPES = {
    "MODEL",
    "CLIP",
    "VAE",
    "CONDITIONING",
    "LATENT",
    "SAMPLER",
    "SIGMAS",
    "GUIDER",
}

NODE_CLASS_MAPPINGS = {"MobileProfileV2DebugExporter": MobileProfileV2DebugExporter}
NODE_DISPLAY_NAME_MAPPINGS = {"MobileProfileV2DebugExporter": "Mobile Profile V2 Debug Exporter"}
