from __future__ import annotations

import hashlib
import json
import time
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


class MobileProfileExporter:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "profile_name": ("STRING", {"default": "Imported Workflow"}),
                "workflow_json_text": ("STRING", {"multiline": True, "default": "{}"}),
                "visibility_mode": (["simple_first", "show_more", "expert"], {"default": "simple_first"}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("export_path",)
    FUNCTION = "export_profile"
    CATEGORY = "mobile_analyzer"

    def export_profile(self, profile_name: str, workflow_json_text: str, visibility_mode: str) -> Tuple[str]:
        workflow = parse_workflow(workflow_json_text)
        workflow_id = hash_json(workflow)
        profile_id = slugify(profile_name) or "imported_workflow"
        app_profile = build_app_profile(workflow, profile_id, profile_name, workflow_id, visibility_mode)

        output_dir = Path("output") / "mobile_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        zip_path = output_dir / f"{profile_id}_{timestamp}.zip"

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("workflow.json", json.dumps(workflow, ensure_ascii=False, indent=2))
            zf.writestr("app_profile.json", json.dumps(app_profile, ensure_ascii=False, indent=2))
            zf.writestr("source_info.json", json.dumps({"source": "manual_text"}, ensure_ascii=False, indent=2))
            zf.writestr("README.txt", "Generated by ComfyUI-Mobile-Analyzer.\n")

        return (str(zip_path),)


def parse_workflow(text: str) -> Dict[str, Any]:
    value = json.loads(text)
    if not isinstance(value, dict):
        raise ValueError("Workflow JSON must be an object")
    return value


def hash_json(value: Dict[str, Any]) -> str:
    raw = json.dumps(value, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return "sha256_" + hashlib.sha256(raw).hexdigest()


def slugify(value: str) -> str:
    chars = []
    for ch in value.lower():
        if ch.isalnum():
            chars.append(ch)
        elif ch in [" ", "-", "_"]:
            chars.append("_")
    return "".join(chars).strip("_")[:80]


def build_app_profile(workflow: Dict[str, Any], profile_id: str, profile_name: str, workflow_id: str, visibility_mode: str) -> Dict[str, Any]:
    nodes = []
    simple_fields = []
    patch_targets = []
    model_refs = []

    sampler_id = find_first_node_by_class(workflow, "KSampler")
    positive_id = find_connected_node_id(workflow, sampler_id, "positive")
    negative_id = find_connected_node_id(workflow, sampler_id, "negative")
    latent_id = find_connected_node_id(workflow, sampler_id, "latent_image")

    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        category, visibility, role = classify_node(class_type, inputs)

        nodes.append({
            "node_id": str(node_id),
            "class_type": class_type,
            "category": category,
            "known": class_type in KNOWN_NODE_TYPES,
            "exists_in_comfyui": None,
            "ui_visibility": visibility,
            "editable": visibility in ["simple", "advanced", "expert"],
            "role": role,
        })

        if class_type == "CLIPTextEncode" and isinstance(inputs.get("text"), str):
            if str(node_id) == str(negative_id):
                add_field(simple_fields, patch_targets, "negative", "Negative Prompt", "textarea", "prompt", node_id, "text", inputs["text"], "STRING")
            elif str(node_id) == str(positive_id) or positive_id is None:
                add_field(simple_fields, patch_targets, "prompt", "Prompt", "textarea", "prompt", node_id, "text", inputs["text"], "STRING")
            else:
                add_field(simple_fields, patch_targets, f"prompt_{node_id}", "Prompt", "textarea", "prompt", node_id, "text", inputs["text"], "STRING")

        if class_type == "KSampler":
            for name, value_type, label, ui_type in [
                ("seed", "INT", "Seed", "number"),
                ("steps", "INT", "Steps", "number"),
                ("cfg", "FLOAT", "CFG", "slider"),
                ("sampler_name", "COMBO", "Sampler", "select"),
                ("scheduler", "COMBO", "Scheduler", "select"),
                ("denoise", "FLOAT", "Denoise", "slider"),
            ]:
                if name in inputs and not is_connection(inputs[name]):
                    add_field(simple_fields, patch_targets, name, label, ui_type, "basic_sampling", node_id, name, inputs[name], value_type)

        if class_type == "EmptyLatentImage" and (latent_id is None or str(node_id) == str(latent_id)):
            for name, value_type, label, field_id in [
                ("width", "INT", "Width", "width"),
                ("height", "INT", "Height", "height"),
                ("batch_size", "INT", "Batch", "batch"),
            ]:
                if name in inputs and not is_connection(inputs[name]):
                    add_field(simple_fields, patch_targets, field_id, label, "number", "size", node_id, name, inputs[name], value_type)

        if class_type == "LoadImage" and isinstance(inputs.get("image"), str):
            add_field(simple_fields, patch_targets, f"input_image_{node_id}", "Input Image", "image", "image_input", node_id, "image", inputs["image"], "IMAGE")

        model_refs.extend(detect_model_refs(class_type, inputs))

    model_refs = dedupe(model_refs)
    warnings = ["object_info and exact model existence checks are not implemented yet."]
    if model_refs:
        warnings.append("Detected model names are listed as unverified references.")

    return {
        "schema_version": "1.0",
        "profile_id": profile_id,
        "profile_name": profile_name,
        "profile_version": "0.2.1",
        "workflow_id": workflow_id,
        "workflow_format": "api",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "source": {"type": "manual", "name": profile_name, "url": "", "note": ""},
        "compatibility": {
            "status": "partial",
            "missing_nodes_count": 0,
            "missing_models_count": len(model_refs),
            "attention_nodes_count": 0,
            "warnings_count": len(warnings),
        },
        "ui": {"simple": simple_fields, "advanced": [], "expert": []},
        "patch_targets": patch_targets,
        "nodes": nodes,
        "missing_nodes": [],
        "missing_models": model_refs,
        "attention_nodes": [],
        "warnings": warnings,
    }


def add_field(fields: List[Dict[str, Any]], patches: List[Dict[str, Any]], field_id: str, label: str, ui_type: str, section: str, node_id: str, input_name: str, default: Any, value_type: str) -> None:
    patch_id = f"patch_{node_id}_{input_name}_{field_id}"
    fields.append({
        "field_id": field_id,
        "label": label,
        "type": ui_type,
        "section": section,
        "ui_visibility": "simple",
        "node_id": str(node_id),
        "input": input_name,
        "default": default,
        "patch_target_id": patch_id,
    })
    patches.append({
        "patch_target_id": patch_id,
        "field_id": field_id,
        "node_id": str(node_id),
        "input": input_name,
        "value_type": value_type,
    })


def classify_node(class_type: str, inputs: Dict[str, Any]):
    if class_type == "KSampler":
        return "sampler", "simple", "main_sampler"
    if class_type == "CLIPTextEncode":
        return "prompt", "simple", "prompt_encoder"
    if class_type == "LoadImage":
        return "image_input", "simple", "input_image"
    if class_type in ["SaveImage", "PreviewImage"]:
        return "image_output", "hidden", "output"
    if class_type in ["VAEEncode", "VAEDecode"]:
        return "vae", "hidden", "pass_through"
    if class_type == "EmptyLatentImage":
        return "latent", "simple", "latent_source"
    if class_type in ["CheckpointLoaderSimple", "UNETLoader", "DualCLIPLoader", "VAELoader"]:
        return "model_loader", "expert", "model_loader"
    if class_type == "LoraLoader":
        return "lora", "advanced", "lora"
    if inputs and all(is_connection(v) for v in inputs.values()):
        return "unknown", "hidden", "pass_through_unknown"
    return "unknown", "expert", "unknown"


def find_first_node_by_class(workflow: Dict[str, Any], class_type: str) -> Optional[str]:
    for node_id, node in workflow.items():
        if isinstance(node, dict) and node.get("class_type") == class_type:
            return str(node_id)
    return None


def find_connected_node_id(workflow: Dict[str, Any], node_id: Optional[str], input_name: str) -> Optional[str]:
    if not node_id or node_id not in workflow:
        return None
    node = workflow.get(node_id, {})
    inputs = node.get("inputs", {}) if isinstance(node, dict) else {}
    value = inputs.get(input_name)
    if is_connection(value):
        return str(value[0])
    return None


def detect_model_refs(class_type: str, inputs: Dict[str, Any]) -> List[Dict[str, Any]]:
    rules = {
        "CheckpointLoaderSimple": [("ckpt_name", "checkpoint", "models/checkpoints")],
        "UNETLoader": [("unet_name", "unet", "models/unet")],
        "VAELoader": [("vae_name", "vae", "models/vae")],
        "LoraLoader": [("lora_name", "lora", "models/loras")],
    }
    refs = []
    for input_name, model_type, path_hint in rules.get(class_type, []):
        value = inputs.get(input_name)
        if isinstance(value, str) and value:
            refs.append({"type": model_type, "name": value, "path_hint": path_hint})
    return refs


def dedupe(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = set()
    result = []
    for item in items:
        key = tuple(sorted(item.items()))
        if key not in seen:
            seen.add(key)
            result.append(item)
    return result


def is_connection(value: Any) -> bool:
    if not isinstance(value, list) or len(value) != 2:
        return False
    return isinstance(value[0], (str, int)) and isinstance(value[1], int)


KNOWN_NODE_TYPES = {
    "KSampler",
    "CLIPTextEncode",
    "LoadImage",
    "SaveImage",
    "PreviewImage",
    "EmptyLatentImage",
    "CheckpointLoaderSimple",
    "UNETLoader",
    "DualCLIPLoader",
    "VAELoader",
    "VAEEncode",
    "VAEDecode",
    "LoraLoader",
}

NODE_CLASS_MAPPINGS = {"MobileProfileExporter": MobileProfileExporter}
NODE_DISPLAY_NAME_MAPPINGS = {"MobileProfileExporter": "Mobile Profile Exporter"}
