from __future__ import annotations

import hashlib
import json
import time
import zipfile
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


class MobileProfileExporter:
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "profile_name": ("STRING", {"default": "Imported Workflow"}),
                "workflow_json_text": ("STRING", {"multiline": True, "default": "{}"}),
                "visibility_mode": (["simple_first", "show_more", "expert"], {"default": "simple_first"}),
            }
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("export_path",)
    FUNCTION = "export_profile"
    CATEGORY = "mobile_analyzer"
    OUTPUT_NODE = True

    def export_profile(self, profile_name: str, workflow_json_text: str, visibility_mode: str) -> Tuple[str]:
        workflow = parse_workflow(workflow_json_text)
        workflow_id = hash_json(workflow)
        profile_id = slugify(profile_name) or "imported_workflow"
        workflow_class_types = collect_workflow_class_types(workflow)
        runtime_node_defs = read_runtime_node_definitions(workflow_class_types)
        operation_candidates = extract_operation_candidates(workflow, runtime_node_defs)
        app_profile = build_app_profile(workflow, profile_id, profile_name, workflow_id, visibility_mode)
        analysis_debug = build_analysis_debug(workflow, runtime_node_defs, operation_candidates)

        output_dir = Path("output") / "mobile_profiles"
        output_dir.mkdir(parents=True, exist_ok=True)
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        zip_path = output_dir / f"{profile_id}_{timestamp}.zip"

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("workflow.json", json.dumps(workflow, ensure_ascii=False, indent=2))
            zf.writestr("app_profile.json", json.dumps(app_profile, ensure_ascii=False, indent=2))
            zf.writestr("analysis_debug.json", json.dumps(analysis_debug, ensure_ascii=False, indent=2))
            zf.writestr(
                "source_info.json",
                json.dumps(
                    {
                        "source": "manual_text",
                        "analysis_debug": "analysis_debug.json",
                        "operation_candidates_count": len(operation_candidates),
                        "runtime_node_definitions_count": len(runtime_node_defs),
                    },
                    ensure_ascii=False,
                    indent=2,
                ),
            )
            zf.writestr("README.txt", "Generated by ComfyUI-Mobile-Analyzer.\n")

        return (str(zip_path),)


def parse_workflow(text: str) -> Dict[str, Any]:
    value = json.loads(text)
    if not isinstance(value, dict):
        raise ValueError("Workflow JSON must be an object")
    return value


def hash_json(value: Dict[str, Any]) -> str:
    raw = json.dumps(value, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return "sha256_" + hashlib.sha256(raw).hexdigest()


def slugify(value: str) -> str:
    chars = []
    for ch in value.lower():
        if ch.isalnum():
            chars.append(ch)
        elif ch in [" ", "-", "_"]:
            chars.append("_")
    return "".join(chars).strip("_")[:80]


def build_app_profile(workflow: Dict[str, Any], profile_id: str, profile_name: str, workflow_id: str, visibility_mode: str) -> Dict[str, Any]:
    nodes = []
    simple_fields = []
    patch_targets = []
    model_refs = []

    sampler_id = find_first_node_by_class(workflow, "KSampler")
    positive_id = find_connected_node_id(workflow, sampler_id, "positive")
    negative_id = find_connected_node_id(workflow, sampler_id, "negative")
    latent_id = find_connected_node_id(workflow, sampler_id, "latent_image")

    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        category, visibility, role = classify_node(class_type, inputs)

        nodes.append({
            "node_id": str(node_id),
            "class_type": class_type,
            "category": category,
            "known": class_type in KNOWN_NODE_TYPES,
            "exists_in_comfyui": None,
            "ui_visibility": visibility,
            "editable": visibility in ["simple", "advanced", "expert"],
            "role": role,
        })

        if class_type == "CLIPTextEncode" and isinstance(inputs.get("text"), str):
            if str(node_id) == str(negative_id):
                add_field(simple_fields, patch_targets, "negative", "Negative Prompt", "textarea", "prompt", node_id, "text", inputs["text"], "STRING")
            elif str(node_id) == str(positive_id) or positive_id is None:
                add_field(simple_fields, patch_targets, "prompt", "Prompt", "textarea", "prompt", node_id, "text", inputs["text"], "STRING")
            else:
                add_field(simple_fields, patch_targets, f"prompt_{node_id}", "Prompt", "textarea", "prompt", node_id, "text", inputs["text"], "STRING")

        if class_type == "KSampler":
            for name, value_type, label, ui_type in [
                ("seed", "INT", "Seed", "number"),
                ("steps", "INT", "Steps", "number"),
                ("cfg", "FLOAT", "CFG", "slider"),
                ("sampler_name", "COMBO", "Sampler", "select"),
                ("scheduler", "COMBO", "Scheduler", "select"),
                ("denoise", "FLOAT", "Denoise", "slider"),
            ]:
                if name in inputs and not is_connection(inputs[name]):
                    add_field(simple_fields, patch_targets, name, label, ui_type, "basic_sampling", node_id, name, inputs[name], value_type)

        if class_type == "EmptyLatentImage" and (latent_id is None or str(node_id) == str(latent_id)):
            for name, value_type, label, field_id in [
                ("width", "INT", "Width", "width"),
                ("height", "INT", "Height", "height"),
                ("batch_size", "INT", "Batch", "batch"),
            ]:
                if name in inputs and not is_connection(inputs[name]):
                    add_field(simple_fields, patch_targets, field_id, label, "number", "size", node_id, name, inputs[name], value_type)

        if class_type == "LoadImage" and isinstance(inputs.get("image"), str):
            add_field(simple_fields, patch_targets, f"input_image_{node_id}", "Input Image", "image", "image_input", node_id, "image", inputs["image"], "IMAGE")

        model_refs.extend(detect_model_refs(class_type, inputs))

    model_refs = dedupe(model_refs)
    warnings = ["object_info and exact model existence checks are not implemented yet."]
    if model_refs:
        warnings.append("Detected model names are listed as unverified references.")

    return {
        "schema_version": "1.0",
        "profile_id": profile_id,
        "profile_name": profile_name,
        "profile_version": "0.2.1",
        "workflow_id": workflow_id,
        "workflow_format": "api",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "source": {"type": "manual", "name": profile_name, "url": "", "note": ""},
        "compatibility": {
            "status": "partial",
            "missing_nodes_count": 0,
            "missing_models_count": len(model_refs),
            "attention_nodes_count": 0,
            "warnings_count": len(warnings),
        },
        "ui": {"simple": simple_fields, "advanced": [], "expert": []},
        "patch_targets": patch_targets,
        "nodes": nodes,
        "missing_nodes": [],
        "missing_models": model_refs,
        "attention_nodes": [],
        "warnings": warnings,
    }


def add_field(fields: List[Dict[str, Any]], patches: List[Dict[str, Any]], field_id: str, label: str, ui_type: str, section: str, node_id: str, input_name: str, default: Any, value_type: str) -> None:
    patch_id = f"patch_{node_id}_{input_name}_{field_id}"
    fields.append({
        "field_id": field_id,
        "label": label,
        "type": ui_type,
        "section": section,
        "ui_visibility": "simple",
        "node_id": str(node_id),
        "input": input_name,
        "default": default,
        "patch_target_id": patch_id,
    })
    patches.append({
        "patch_target_id": patch_id,
        "field_id": field_id,
        "node_id": str(node_id),
        "input": input_name,
        "value_type": value_type,
    })


def build_analysis_debug(workflow: Dict[str, Any], runtime_node_defs: Dict[str, Any], operation_candidates: List[Dict[str, Any]]) -> Dict[str, Any]:
    class_types = sorted(collect_workflow_class_types(workflow))
    missing_runtime_defs = [class_type for class_type in class_types if class_type not in runtime_node_defs]
    return {
        "schema_version": "analysis_debug.0.1",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "purpose": "Debug-only capability extraction output. Current MVP app_profile.json remains v1-compatible.",
        "workflow_summary": {
            "node_count": count_workflow_nodes(workflow),
            "class_types": class_types,
        },
        "runtime_node_definitions": {
            "found_count": len(runtime_node_defs),
            "missing_class_types": missing_runtime_defs,
            "definitions": runtime_node_defs,
        },
        "operation_candidates": operation_candidates,
        "candidate_summary": summarize_operation_candidates(operation_candidates),
        "safety_note": "These are operation candidates, not final editable fields. Validator-gated patch_targets are still required before app exposure.",
    }


def collect_workflow_class_types(workflow: Dict[str, Any]) -> set[str]:
    class_types: set[str] = set()
    for node in workflow.values():
        if isinstance(node, dict):
            class_type = node.get("class_type")
            if class_type:
                class_types.add(str(class_type))
    return class_types


def count_workflow_nodes(workflow: Dict[str, Any]) -> int:
    return sum(1 for value in workflow.values() if isinstance(value, dict) and "class_type" in value)


def read_runtime_node_definitions(class_types: Iterable[str]) -> Dict[str, Any]:
    """Read ComfyUI runtime node metadata when available.

    This is intentionally best-effort. The Analyzer must still preserve workflows
    when runtime metadata cannot be read.
    """
    try:
        import nodes as comfy_nodes  # type: ignore
    except Exception:
        return {}

    mappings = getattr(comfy_nodes, "NODE_CLASS_MAPPINGS", {})
    if not isinstance(mappings, dict):
        return {}

    result: Dict[str, Any] = {}
    for class_type in sorted(set(str(item) for item in class_types)):
        node_class = mappings.get(class_type)
        if node_class is None:
            continue
        result[class_type] = extract_runtime_node_definition(class_type, node_class)
    return result


def extract_runtime_node_definition(class_type: str, node_class: Any) -> Dict[str, Any]:
    input_types: Dict[str, Any] = {}
    input_error: Optional[str] = None
    try:
        input_types_fn = getattr(node_class, "INPUT_TYPES", None)
        if callable(input_types_fn):
            raw_input_types = input_types_fn()
            if isinstance(raw_input_types, dict):
                input_types = normalize_input_types(raw_input_types)
    except Exception as exc:
        input_error = f"{type(exc).__name__}: {exc}"

    return {
        "class_type": class_type,
        "category": to_json_safe(getattr(node_class, "CATEGORY", None)),
        "return_types": to_json_safe(getattr(node_class, "RETURN_TYPES", None)),
        "return_names": to_json_safe(getattr(node_class, "RETURN_NAMES", None)),
        "function": to_json_safe(getattr(node_class, "FUNCTION", None)),
        "output_node": bool(getattr(node_class, "OUTPUT_NODE", False)),
        "inputs": input_types,
        "input_error": input_error,
    }


def normalize_input_types(raw_input_types: Dict[str, Any]) -> Dict[str, Any]:
    normalized: Dict[str, Any] = {}
    for group_name in ["required", "optional", "hidden"]:
        raw_group = raw_input_types.get(group_name, {})
        if not isinstance(raw_group, dict):
            continue
        normalized[group_name] = {}
        for input_name, spec in raw_group.items():
            normalized[group_name][str(input_name)] = normalize_input_spec(spec)
    return normalized


def normalize_input_spec(spec: Any) -> Dict[str, Any]:
    raw_type: Any = None
    config: Dict[str, Any] = {}
    options: Optional[List[Any]] = None

    if isinstance(spec, tuple) and spec:
        raw_type = spec[0]
        if len(spec) > 1 and isinstance(spec[1], dict):
            config = spec[1]
    elif isinstance(spec, list):
        raw_type = spec
    elif isinstance(spec, str):
        raw_type = spec
    else:
        raw_type = type(spec).__name__

    if isinstance(raw_type, list):
        options = [to_json_safe(value) for value in raw_type]
        comfy_type = "COMBO"
    else:
        comfy_type = str(raw_type)

    return {
        "raw_type": comfy_type,
        "normalized_value_type": normalize_value_type(comfy_type),
        "candidate_control_type": default_control_type(comfy_type, config=config),
        "config": to_json_safe(config),
        "options": options,
    }


def extract_operation_candidates(workflow: Dict[str, Any], runtime_node_defs: Dict[str, Any]) -> List[Dict[str, Any]]:
    candidates: List[Dict[str, Any]] = []
    for node_id, node in workflow.items():
        if not isinstance(node, dict):
            continue
        class_type = str(node.get("class_type", "Unknown"))
        inputs = node.get("inputs", {}) if isinstance(node.get("inputs", {}), dict) else {}
        runtime_def = runtime_node_defs.get(class_type, {}) if isinstance(runtime_node_defs.get(class_type, {}), dict) else {}
        runtime_inputs = runtime_def.get("inputs", {}) if isinstance(runtime_def.get("inputs", {}), dict) else {}

        for input_name, current_value in inputs.items():
            if is_connection(current_value):
                continue
            input_meta, input_group = find_runtime_input_meta(runtime_inputs, str(input_name))
            inferred_type = infer_input_type(str(input_name), current_value)
            raw_type = str(input_meta.get("raw_type") or inferred_type)
            normalized_value_type = str(input_meta.get("normalized_value_type") or normalize_value_type(raw_type))
            control_type = str(input_meta.get("candidate_control_type") or default_control_type(raw_type, input_name=str(input_name)))
            section_hint = section_hint_for_candidate(class_type, str(input_name), raw_type, control_type)
            safety_hint = safety_hint_for_candidate(raw_type, control_type, str(input_name))
            candidate_id = f"candidate_{node_id}_{input_name}"

            candidates.append({
                "candidate_id": candidate_id,
                "node_id": str(node_id),
                "class_type": class_type,
                "input": str(input_name),
                "input_group": input_group,
                "raw_type": raw_type,
                "normalized_value_type": normalized_value_type,
                "candidate_control_type": control_type,
                "current_value": to_json_safe(current_value),
                "source_confidence": "runtime_definition" if input_meta else "value_inference",
                "known_runtime_definition": bool(runtime_def),
                "known_input_definition": bool(input_meta),
                "section_hint": section_hint,
                "safety_hint": safety_hint,
                "notes": candidate_notes(class_type, str(input_name), raw_type, input_meta),
            })

    return candidates


def find_runtime_input_meta(runtime_inputs: Dict[str, Any], input_name: str) -> Tuple[Dict[str, Any], Optional[str]]:
    for group_name in ["required", "optional", "hidden"]:
        group = runtime_inputs.get(group_name, {})
        if isinstance(group, dict) and isinstance(group.get(input_name), dict):
            return group[input_name], group_name
    return {}, None


def infer_input_type(input_name: str, value: Any) -> str:
    lower_name = input_name.lower()
    if lower_name in {"image", "init_image", "reference_image"} or lower_name.endswith("_image"):
        return "IMAGE" if isinstance(value, str) else "UNKNOWN"
    if "mask" in lower_name:
        return "MASK" if isinstance(value, str) else "UNKNOWN"
    if "audio" in lower_name or "voice" in lower_name or lower_name in {"bgm", "sound"}:
        return "AUDIO" if isinstance(value, str) else "UNKNOWN"
    if "video" in lower_name or lower_name in {"movie", "clip"}:
        return "VIDEO" if isinstance(value, str) else "UNKNOWN"
    if lower_name in MODEL_PICKER_INPUT_NAMES:
        return "COMBO"
    if isinstance(value, bool):
        return "BOOLEAN"
    if isinstance(value, int) and not isinstance(value, bool):
        return "INT"
    if isinstance(value, float):
        return "FLOAT"
    if isinstance(value, str):
        return "STRING"
    if isinstance(value, (list, dict)):
        return "JSON"
    return "UNKNOWN"


def normalize_value_type(raw_type: str) -> str:
    upper_type = raw_type.upper()
    if upper_type in {"STRING", "COMBO"}:
        return "string"
    if upper_type in {"INT", "INTEGER"}:
        return "integer"
    if upper_type in {"FLOAT", "DOUBLE", "NUMBER"}:
        return "float"
    if upper_type in {"BOOLEAN", "BOOL"}:
        return "boolean"
    if upper_type in {"IMAGE"}:
        return "image"
    if upper_type in {"MASK"}:
        return "mask"
    if upper_type in {"AUDIO"}:
        return "audio"
    if upper_type in {"VIDEO"}:
        return "video"
    if upper_type in {"JSON"}:
        return "json"
    return "unknown"


def default_control_type(raw_type: str, config: Optional[Dict[str, Any]] = None, input_name: str = "") -> str:
    upper_type = raw_type.upper()
    config = config or {}
    lower_name = input_name.lower()

    if upper_type == "STRING":
        if config.get("multiline") or any(token in lower_name for token in ["prompt", "text", "caption", "template"]):
            return "textarea"
        return "text"
    if upper_type in {"INT", "INTEGER"}:
        if "seed" in lower_name:
            return "seed"
        return "integer"
    if upper_type in {"FLOAT", "DOUBLE", "NUMBER"}:
        return "slider" if any(key in config for key in ["min", "max", "step"]) else "float"
    if upper_type in {"BOOLEAN", "BOOL"}:
        return "switch"
    if upper_type == "COMBO":
        if lower_name in MODEL_PICKER_INPUT_NAMES or lower_name.endswith("_name"):
            return "model_picker"
        return "select"
    if upper_type == "IMAGE":
        return "image_upload"
    if upper_type == "MASK":
        return "mask_editor"
    if upper_type == "AUDIO":
        return "audio_upload"
    if upper_type == "VIDEO":
        return "video_upload"
    if upper_type == "JSON":
        return "readonly"
    return "unknown"


def section_hint_for_candidate(class_type: str, input_name: str, raw_type: str, control_type: str) -> str:
    lower_class = class_type.lower()
    lower_input = input_name.lower()

    if "prompt" in lower_input or lower_input in {"text", "system_prompt", "negative"}:
        return "core"
    if lower_input in {"seed", "steps", "cfg", "denoise", "sampler_name", "scheduler", "width", "height", "batch_size"}:
        return "basic"
    if "lora" in lower_class or "lora" in lower_input:
        return "model"
    if "controlnet" in lower_class or "control" in lower_input:
        return "advanced"
    if control_type in {"image_upload", "mask_editor", "audio_upload", "video_upload", "file_upload"}:
        return "media"
    if control_type in {"model_picker", "select"}:
        return "model"
    if raw_type.upper() in {"STRING", "INT", "FLOAT", "BOOLEAN", "COMBO"}:
        return "expert_unknown" if class_type not in KNOWN_NODE_TYPES else "advanced"
    return "hidden"


def safety_hint_for_candidate(raw_type: str, control_type: str, input_name: str) -> str:
    upper_type = raw_type.upper()
    lower_name = input_name.lower()
    if lower_name in {"api_key", "token", "password", "secret", "credential"} or "api_key" in lower_name:
        return "sensitive_disable_by_default"
    if "path" in lower_name or "url" in lower_name:
        return "file_or_network_review_required"
    if upper_type in {"STRING", "INT", "FLOAT", "BOOLEAN", "COMBO", "IMAGE", "MASK", "AUDIO", "VIDEO"}:
        return "candidate_requires_validator"
    if control_type == "readonly":
        return "preserve_only"
    return "unknown_preserve_by_default"


def candidate_notes(class_type: str, input_name: str, raw_type: str, input_meta: Dict[str, Any]) -> List[str]:
    notes: List[str] = []
    if not input_meta:
        notes.append("Runtime input definition missing; type inferred from current value/name.")
    if class_type not in KNOWN_NODE_TYPES:
        notes.append("Unknown or not-yet-semantic-classified node; expose only after validator approval.")
    if raw_type.upper() in NON_WIDGET_RUNTIME_TYPES:
        notes.append("Runtime type is normally connection-oriented; keep read-only unless a known safe widget pattern exists.")
    return notes


def summarize_operation_candidates(candidates: List[Dict[str, Any]]) -> Dict[str, Any]:
    by_type: Dict[str, int] = {}
    by_control: Dict[str, int] = {}
    by_safety: Dict[str, int] = {}
    for candidate in candidates:
        by_type[str(candidate.get("raw_type", "unknown"))] = by_type.get(str(candidate.get("raw_type", "unknown")), 0) + 1
        by_control[str(candidate.get("candidate_control_type", "unknown"))] = by_control.get(str(candidate.get("candidate_control_type", "unknown")), 0) + 1
        by_safety[str(candidate.get("safety_hint", "unknown"))] = by_safety.get(str(candidate.get("safety_hint", "unknown")), 0) + 1
    return {
        "total": len(candidates),
        "by_raw_type": dict(sorted(by_type.items())),
        "by_candidate_control_type": dict(sorted(by_control.items())),
        "by_safety_hint": dict(sorted(by_safety.items())),
    }


def classify_node(class_type: str, inputs: Dict[str, Any]):
    if class_type == "KSampler":
        return "sampler", "simple", "main_sampler"
    if class_type == "CLIPTextEncode":
        return "prompt", "simple", "prompt_encoder"
    if class_type == "LoadImage":
        return "image_input", "simple", "input_image"
    if class_type in ["SaveImage", "PreviewImage"]:
        return "image_output", "hidden", "output"
    if class_type in ["VAEEncode", "VAEDecode"]:
        return "vae", "hidden", "pass_through"
    if class_type == "EmptyLatentImage":
        return "latent", "simple", "latent_source"
    if class_type in ["CheckpointLoaderSimple", "UNETLoader", "DualCLIPLoader", "VAELoader"]:
        return "model_loader", "expert", "model_loader"
    if class_type == "LoraLoader":
        return "lora", "advanced", "lora"
    if inputs and all(is_connection(v) for v in inputs.values()):
        return "unknown", "hidden", "pass_through_unknown"
    return "unknown", "expert", "unknown"


def find_first_node_by_class(workflow: Dict[str, Any], class_type: str) -> Optional[str]:
    for node_id, node in workflow.items():
        if isinstance(node, dict) and node.get("class_type") == class_type:
            return str(node_id)
    return None


def find_connected_node_id(workflow: Dict[str, Any], node_id: Optional[str], input_name: str) -> Optional[str]:
    if not node_id or node_id not in workflow:
        return None
    node = workflow.get(node_id, {})
    inputs = node.get("inputs", {}) if isinstance(node, dict) else {}
    value = inputs.get(input_name)
    if is_connection(value):
        return str(value[0])
    return None


def detect_model_refs(class_type: str, inputs: Dict[str, Any]) -> List[Dict[str, Any]]:
    rules = {
        "CheckpointLoaderSimple": [("ckpt_name", "checkpoint", "models/checkpoints")],
        "UNETLoader": [("unet_name", "unet", "models/unet")],
        "VAELoader": [("vae_name", "vae", "models/vae")],
        "LoraLoader": [("lora_name", "lora", "models/loras")],
    }
    refs = []
    for input_name, model_type, path_hint in rules.get(class_type, []):
        value = inputs.get(input_name)
        if isinstance(value, str) and value:
            refs.append({"type": model_type, "name": value, "path_hint": path_hint})
    return refs


def dedupe(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = set()
    result = []
    for item in items:
        key = tuple(sorted(item.items()))
        if key not in seen:
            seen.add(key)
            result.append(item)
    return result


def is_connection(value: Any) -> bool:
    if not isinstance(value, list) or len(value) != 2:
        return False
    return isinstance(value[0], (str, int)) and isinstance(value[1], int)


def to_json_safe(value: Any) -> Any:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, tuple):
        return [to_json_safe(item) for item in value]
    if isinstance(value, list):
        return [to_json_safe(item) for item in value]
    if isinstance(value, dict):
        return {str(key): to_json_safe(item) for key, item in value.items()}
    return str(value)


KNOWN_NODE_TYPES = {
    "KSampler",
    "CLIPTextEncode",
    "LoadImage",
    "SaveImage",
    "PreviewImage",
    "EmptyLatentImage",
    "CheckpointLoaderSimple",
    "UNETLoader",
    "DualCLIPLoader",
    "VAELoader",
    "VAEEncode",
    "VAEDecode",
    "LoraLoader",
}

MODEL_PICKER_INPUT_NAMES = {
    "ckpt_name",
    "checkpoint",
    "unet_name",
    "vae_name",
    "clip_name",
    "lora_name",
    "control_net_name",
    "controlnet_name",
    "model_name",
    "sampler_name",
    "scheduler",
}

NON_WIDGET_RUNTIME_TYPES = {
    "MODEL",
    "CLIP",
    "VAE",
    "CONDITIONING",
    "LATENT",
    "SAMPLER",
    "SIGMAS",
    "GUIDER",
}

NODE_CLASS_MAPPINGS = {"MobileProfileExporter": MobileProfileExporter}
NODE_DISPLAY_NAME_MAPPINGS = {"MobileProfileExporter": "Mobile Profile Exporter"}
